### ISSUE TITLE
老哥，这个插件不太好使

### ISSUE THREAD

**Issue by yimao009** [chuanci/iconfont#5]
➜ flutter packages pub run iconfont 
Unhandled exception:
Bad state: No element
#0      List.last (dart:core-patch/growable_array.dart:337:5)
#1      IconBuild._scanDir.<anonymous closure> (package:iconfont/src/icon_build.dart:114:52)
#2      List.forEach (dart:core-patch/growable_array.dart:403:8)
#3      IconBuild._scanDir (package:iconfont/src/icon_build.dart:102:66)
#4      IconBuild.build (package:iconfont/src/icon_build.dart:39:11)
<asynchronous suspension>
pub finished with exit code 255

**Comment by chuanci** [comment]
-i -o 指定参数不以“/”结尾,会报错

2.0.0 修复
